name: Upload Compose File to GHCR

on:
  push:
    paths:
      - 'docker-compose.prod.yml'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to use'
        required: true
        default: 'master'

permissions:
  contents: read
  packages: write

jobs:
  upload-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}

      - name: Convert owner to lowercase
        run: |
          LOWERCASE_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "LOWERCASE_OWNER=$LOWERCASE_OWNER" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Upload compose file as config
        run: |
          # Verify file exists
          ls -la docker-compose.prod.yml || exit 1

          # Create temporary Dockerfile
          cat <<EOF > Dockerfile.temp
          FROM scratch
          COPY docker-compose.prod.yml /docker-compose.prod.yml
          EOF

          # Build and push config image
          docker buildx build \
            -f Dockerfile.temp \
            -t ghcr.io/${{ env.LOWERCASE_OWNER }}/devcanvas-config:latest \
            -t ghcr.io/${{ env.LOWERCASE_OWNER }}/devcanvas-config:${{ github.sha }} \
            --push \
            --platform linux/amd64 .