name: Upload Compose File to GHCR

on:
  push:
    paths:
      - 'docker-compose.prod.yml'

permissions:
  contents: read
  packages: write

jobs:
  upload-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Upload as config
        run: |
          docker buildx create --use
          echo "Uploading compose file as config..."
          echo -n "docker-compose-" > compose-name.txt
          echo ${{ github.sha }} >> compose-name.txt
          docker buildx build --file docker-compose.prod.yml \
            --tag ghcr.io/${{ github.repository_owner }}/devcanvas-config:latest \
            --output type=image,name=ghcr.io/${{ github.repository_owner }}/devcanvas-config:latest,push=true \
            --platform linux/amd64 .
